### ISSUE TITLE
"SemanticVersioning.moon" is not present

### ISSUE THREAD

**Issue by Totto16** [TypesettingTools/DependencyControl#18]
Since Some updates in 2017 "l0.DependencyControl.SemanticVersioning" is used and needed to work.
But this is file/ class isn't in this repo, wher is that? The releases all ship without this, the files there also don't require that module/class.

**Comment by CoffeeFlux** [comment]
As I recall, this is an artifact of incorrectly backporting code from the sqlite branch. If you check out the last stable, it should be fine.

**Comment by Totto16** [comment]
I didn't look into that brabch, since I thought github search would cover that, but apparently it didn't, a console would have done the job, sorry :sweat:
