### ISSUE TITLE
Missing SemanticVersioning.moon

### ISSUE THREAD

**Issue by kagayakuhari** [TypesettingTools/DependencyControl#21]
_@ those who want to install Dependency Control on Linux: If you are keen on working your way around installing this on a Linux system, you can easily do so by spending some 30 minutes doing reverse engineering on an old Release._ 

Title says it all. ``SemanticVersioning.moon`` is missing from ``modules/DependencyControl`` and this repository's Dependency Control version cannot be properly installed if you are reckless enough to try using cutting-edge instead of release. This might not be the only issue this repository has, but it is one that would take quite a lot of messing around to fix properly on one's end, unless you use an older codebase without SemanticVersioning like I did.

I think I could provide a dummy ``SemanticVersioning.moon`` file as a pull request when/if I found a bit of spare time, but I assumed opening an issue would be the best course of action, since you would probably have such file, uncomitted, in your repository.

If this is intended, however, feel free to close this issue.

**Comment by arch1t3cht** [comment]
If all you want is a working install, you can use one of the latest version tags like 0.6.4-alpha instead of master.

**Comment by kagayakuhari** [comment]
That is what I did and it works fine. I just assumed a file could have been misplaced, as there is no real warning mentioning how compiling directly from master will not work.

One could assume that the instruction
> Download the latest DependencyControl release [...]

in _Install instructions_ would imply this codebase is not useable, but I do not think so.

In any case, it has been years since the commit was made.

**Comment by kagayakuhari** [comment]
I will be closing this issue as I believe there is no _actual issue_, it is just a deliberate choice by the developers.
