### ISSUE TITLE
Error installing DependencyControl scripts

### ISSUE THREAD

**Issue by rothosen** [TypesettingTools/DependencyControl#8]
Since there aren't any Aegisub builds for OSX with built-in DependencyControl available, I tried to install by myself following the installation instructions but I can't get to make the script work. Can anyone help me to solve this problem?

Here is the log:

02:34:55: A script in the Automation autoload directory failed to load.
Please review the errors, fix them and use the Rescan Autoload Dir button in Automation Manager to load the scripts again.
02:34:55: Failed to load Automation script '/Users/toshiacunacortez/Library/Application Support/Aegisub/automation/autoload/l0.DependencyControl.Toolbox.moon':
Error initialising Lua script "l0.DependencyControl.Toolbox.moon":

[string "/Users/toshiacunacortez/Library/Application S..."]:13: FFI could not load "PT.PreciseTimer.PreciseTimer". Search paths:
  - "/Users/toshiacunacortez/Library/Application Support/Aegisub/automation/autoload/PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(/Users/toshiacunacortez/Library/Application Support/Aegisub/automation/autoload/PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "/Users/toshiacunacortez/Library/Application Support/Aegisub/automation/include/PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(/Users/toshiacunacortez/Library/Application Support/Aegisub/automation/include/PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "/Applications/Aegisub.app/Contents/SharedSupport/automation/include/PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(/Applications/Aegisub.app/Contents/SharedSupport/automation/include/PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "./PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(./PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "/usr/local/share/luajit-2.0.3/PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(/usr/local/share/luajit-2.0.3/PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "/usr/local/share/lua/5.1/PT/PreciseTimer/libPreciseTimer.dylib" (dlopen(/usr/local/share/lua/5.1/PT/PreciseTimer/libPreciseTimer.dylib, 5): image not found)
  - "PreciseTimer" (dlopen(libPreciseTimer.dylib, 5): image not found)

**Comment by torque** [comment]
Unfortunately, the release archive for macOS has some misnamed files in it. In the following file tree, I have emphasized the two files that will be renamed using the syntax `original name --> new name`. I have shown these in the folder structure as bundled in the 7zip file, but if you have installed them correctly, the files in question should be in `/Users/<user>/Library/Application Support/Aegisub/automation/include/DM/DownloadManager/` and `/Users/<user>/Library/Application Support/Aegisub/automation/include/PT/PreciseTimer/`.

<pre>
DependencyControl-v0.6.3-OSX-x86_64
├── LICENSE
├── README.md
├── autoload
│   └── l0.DependencyControl.Toolbox.moon
├── include
│   ├── BM
│   │   ├── BadMutex
│   │   │   └── libBadMutex.dylib
│   │   └── BadMutex.lua
│   ├── DM
│   │   ├── DownloadManager
│   │   │   └── <b><i>libDownloadManager-osx64.dylib --> libDownloadManager.dylib</i></b>
│   │   └── DownloadManager.lua
│   ├── PT
│   │   ├── PreciseTimer
│   │   │   └── <b><i>libPreciseTimer-osx64.dylib --> libPreciseTimer.dylib</i></b>
│   │   └── PreciseTimer.lua
</pre>

**Comment by rothosen** [comment]
Thank you very much! It works now!

**Comment by SSgumS** [comment]
thanks for this great tool.
you have built windows and osx packages. could you plz build it for linux too?

**Comment by CoffeeFlux** [comment]
Updated the release to use newer builds and fix the naming issue. Closing.
